version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TG_ACCESS_TOKEN=${TG_ACCESS_TOKEN}
      - TIME_ZONE_SETTINGS=${TIME_ZONE_SETTINGS}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  celery:
    build: .
    tty: true
    command: celery -A habbits_tracker worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A habbits_tracker beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data: